sudo: false
dist: trusty
language: node_js
node_js:
  - 10.2.1
env:
  - MONGODB_VERSION=stable MONGODB_TOPOLOGY=standalone
  - MONGODB_VERSION=stable MONGODB_TOPOLOGY=cluster
before_install:
  - npm i -g npm
script:
  - npm run check
  - npm test
