language: node_js
sudo: required
node_js:
- 6.3.1
- lts/boron
script: npm run-script ci
cache:
  directories:
  - node_modules
env:
  matrix:
  - MONGODB_VERSION=3.2.x MONGODB_TOPOLOGY=standalone
  - USE_MONGODB_URL=1
  global:
    secure: grXkzXjsAEE4/PsBCW9iLWuydTibZzHGl462CEPj6TnCfTlP/nRxp5sI0LTEx4mLZZ7dv+g3oTmtohFbSVA4lJvB0/HnObc4mCsnF/z5j8/RZeIDxfH9hPw88Otc6ArSfIjE6HSNHB8D28J6idexRAF4jB5n/JFFeqVR9b0Md2lygcwHsoJjzcl7GmnsOkqp3Xq1DHzluPbU5RfvbH1XBlltRUl5TRgNY6DuNs9E8gtSWN97bRK7+HC+ylz3/Y+NA/M8TkfvwsHjfkBio8O/cHnZwNVEE/KFmYN0N2uHE/J9ccV+CbRloNdqIh5eV2MToC6625nxro+l6+zpJsD9oo/zEExBSqZrf5tQVwzH69lADm9gyEFzZK5oArG4v7Pt96pPgD9Qoj7lpZ5V31rDLnsKVccOTYlDKfjFcREY/olI+jH/L47yq38tv6GgrVbsCAyuMCAqIa0GeVHds3GHJVPr7b5InoohSLJlxNOqftR15PZljYlBQSN+X9JSYvO8YQMEATCiPCqY3ebdZQTl05+Ix8PQRcTBeFfqovSZ7rrrr/NlN0fqQNDRZUkiQIbyFzoF6ZUoK2d4CHwwg846oTR8EIGZc3H5UKdy0MnrPe5KO3co90c0tg9APIXQtEvvgUHEudo0MdKoUzqfAj4rU2JiqDSVANnf2f6cQYuJSUE=
